import { MD3LightTheme as DefaultTheme, MD3DarkTheme, MD3Theme } from 'react-native-paper';
import {
  DefaultTheme as NavigationLightTheme,
  DarkTheme as NavigationDarkTheme,
} from '@react-navigation/native';

export const LightTheme: MD3Theme = {
  ...DefaultTheme,
  dark: false,
  colors: {
    ...DefaultTheme.colors,
    primary: '#162245',
    onPrimary: '#FFFFFF',
    secondary: '#03A9F4',
    onSecondary: '#142144',
    background: '#FFFFFF',
    surface: '#DADADA',
    onSurface: '#7f8f9d',
    onSurfaceVariant: '#FFFFFF',
    error: '#B00020',
    onError: '#FFFFFF',
    outline: '#a6a6a6',
    surfaceVariant: '#000000',
  },
  roundness: 8,
  fonts: {
    default: {
        fontFamily: 'Work Sans',
        fontWeight: '400',
        letterSpacing: 0,
    },
    displayLarge: {
      fontFamily: 'Work Sans',
      fontWeight: '700',
      fontSize: 57,
      lineHeight: 64,
      letterSpacing: 0,
    },
    displayMedium: {
      fontFamily: 'Work Sans',
      fontWeight: '700',
      fontSize: 45,
      lineHeight: 52,
      letterSpacing: 0,
    },
    displaySmall: {
      fontFamily: 'Work Sans',
      fontWeight: '700',
      fontSize: 36,
      lineHeight: 44,
      letterSpacing: 0,
    },
    headlineLarge: {
      fontFamily: 'Work Sans',
      fontWeight: '700',
      fontSize: 32,
      lineHeight: 40,
      letterSpacing: 0,
    },
    headlineMedium: {
      fontFamily: 'Work Sans',
      fontWeight: '700',
      fontSize: 28,
      lineHeight: 36,
      letterSpacing: 0,
    },
    headlineSmall: {
      fontFamily: 'Work Sans',
      fontWeight: '700',
      fontSize: 24,
      lineHeight: 32,
      letterSpacing: 0,
    },
    titleLarge: {
      fontFamily: 'Work Sans',
      fontWeight: '600',
      fontSize: 22,
      lineHeight: 28,
      letterSpacing: 0,
    },
    titleMedium: {
      fontFamily: 'Work Sans',
      fontWeight: '600',
      fontSize: 16,
      lineHeight: 24,
      letterSpacing: 0.15,
    },
    titleSmall: {
      fontFamily: 'Work Sans',
      fontWeight: '600',
      fontSize: 14,
      lineHeight: 20,
      letterSpacing: 0.1,
    },
    labelLarge: {
      fontFamily: 'Work Sans',
      fontWeight: '500',
      fontSize: 14,
      lineHeight: 20,
      letterSpacing: 0.1,
    },
    labelMedium: {
      fontFamily: 'Work Sans',
      fontWeight: '500',
      fontSize: 12,
      lineHeight: 16,
      letterSpacing: 0.5,
    },
    labelSmall: {
      fontFamily: 'Work Sans',
      fontWeight: '500',
      fontSize: 11,
      lineHeight: 16,
      letterSpacing: 0.5,
    },
    bodyLarge: {
      fontFamily: 'Work Sans',
      fontWeight: '400',
      fontSize: 32,
      lineHeight: 32,
      letterSpacing: 0.5,
    },
    bodyMedium: {
      fontFamily: 'Work Sans',
      fontWeight: '400',
      fontSize: 14,
      lineHeight: 20,
      letterSpacing: 0.25,
    },
    bodySmall: {
      fontFamily: 'Work Sans',
      fontWeight: '400',
      fontSize: 12,
      lineHeight: 16,
      letterSpacing: 0.4,
    },
  },
};

export const DarkTheme: MD3Theme = {
  ...MD3DarkTheme,
  dark: true,
  colors: {
    ...MD3DarkTheme.colors,
    primary: '#6C8AE4',
    onPrimary: '#FFFFFF',
    secondary: '#4FC3F7',
    onSecondary: '#142144',
    background: '#0E141F',
    surface: '#1C2333',
    onSurface: '#C0C9D2',
    error: '#CF6679',
    onError: '#000000',
    outline: '#4A5568',
    surfaceVariant: '#2A3145',
  },
  roundness: 8,
  fonts: {
    default: {
      fontFamily: 'Work Sans',
      fontWeight: '400',
      letterSpacing: 0,
    },
    displayLarge: {
      fontFamily: 'Work Sans',
      fontWeight: '700',
      fontSize: 57,
      lineHeight: 64,
      letterSpacing: 0,
    },
    displayMedium: {
      fontFamily: 'Work Sans',
      fontWeight: '700',
      fontSize: 45,
      lineHeight: 52,
      letterSpacing: 0,
    },
    displaySmall: {
      fontFamily: 'Work Sans',
      fontWeight: '700',
      fontSize: 36,
      lineHeight: 44,
      letterSpacing: 0,
    },
    headlineLarge: {
      fontFamily: 'Work Sans',
      fontWeight: '700',
      fontSize: 32,
      lineHeight: 40,
      letterSpacing: 0,
    },
    headlineMedium: {
      fontFamily: 'Work Sans',
      fontWeight: '700',
      fontSize: 28,
      lineHeight: 36,
      letterSpacing: 0,
    },
    headlineSmall: {
      fontFamily: 'Work Sans',
      fontWeight: '700',
      fontSize: 24,
      lineHeight: 32,
      letterSpacing: 0,
    },
    titleLarge: {
      fontFamily: 'Work Sans',
      fontWeight: '600',
      fontSize: 22,
      lineHeight: 28,
      letterSpacing: 0,
    },
    titleMedium: {
      fontFamily: 'Work Sans',
      fontWeight: '600',
      fontSize: 16,
      lineHeight: 24,
      letterSpacing: 0.15,
    },
    titleSmall: {
      fontFamily: 'Work Sans',
      fontWeight: '600',
      fontSize: 14,
      lineHeight: 20,
      letterSpacing: 0.1,
    },
    labelLarge: {
      fontFamily: 'Work Sans',
      fontWeight: '500',
      fontSize: 14,
      lineHeight: 20,
      letterSpacing: 0.1,
    },
    labelMedium: {
      fontFamily: 'Work Sans',
      fontWeight: '500',
      fontSize: 12,
      lineHeight: 16,
      letterSpacing: 0.5,
    },
    labelSmall: {
      fontFamily: 'Work Sans',
      fontWeight: '500',
      fontSize: 11,
      lineHeight: 16,
      letterSpacing: 0.5,
    },
    bodyLarge: {
      fontFamily: 'Work Sans',
      fontWeight: '400',
      fontSize: 16,
      lineHeight: 24,
      letterSpacing: 0.5,
    },
    bodyMedium: {
      fontFamily: 'Work Sans',
      fontWeight: '400',
      fontSize: 14,
      lineHeight: 20,
      letterSpacing: 0.25,
    },
    bodySmall: {
      fontFamily: 'Work Sans',
      fontWeight: '400',
      fontSize: 12,
      lineHeight: 16,
      letterSpacing: 0.4,
    },
  },
};

export const CombinedLightTheme = {
  dark: false,
  roundness: LightTheme.roundness,
  version: 3,
  isV3: true,
  colors: {
    ...NavigationLightTheme.colors,
    ...LightTheme.colors,
  },
};

export const CombinedDarkTheme = {
  dark: true,
  roundness: MD3DarkTheme.roundness,
  version: 3,
  isV3: true,
  colors: {
    ...NavigationDarkTheme.colors,
    ...MD3DarkTheme.colors,
  },
};
