import { MD3LightTheme as DefaultTheme, MD3Theme } from 'react-native-paper';

export const theme: MD3Theme = {
  ...DefaultTheme,
  colors: {
    ...DefaultTheme.colors,
    primary: '#142144',
    onPrimary: '#FFFFFF',
    secondary: '#03A9F4',
    onSecondary: '#142144',
    background: '#F8F9FA',
    surface: '#FFFFFF',
    onSurface: '#7f8f9d',
    error: '#B00020',
    onError: '#FFFFFF',
    outline: '#a6a6a6',
    surfaceVariant: '#F1F2F4',
  },
  roundness: 8,
  fonts: {
    default: {
        fontFamily: 'Work Sans',
        fontWeight: '400',
        letterSpacing: 0,
    },
    displayLarge: {
      fontFamily: 'ITC Bengular',
      fontWeight: '700',
      fontSize: 57,
      lineHeight: 64,
      letterSpacing: 0,
    },
    displayMedium: {
      fontFamily: 'ITC Bengular',
      fontWeight: '700',
      fontSize: 45,
      lineHeight: 52,
      letterSpacing: 0,
    },
    displaySmall: {
      fontFamily: 'ITC Bengular',
      fontWeight: '700',
      fontSize: 36,
      lineHeight: 44,
      letterSpacing: 0,
    },
    headlineLarge: {
      fontFamily: 'ITC Bengular',
      fontWeight: '700',
      fontSize: 32,
      lineHeight: 40,
      letterSpacing: 0,
    },
    headlineMedium: {
      fontFamily: 'ITC Bengular',
      fontWeight: '700',
      fontSize: 28,
      lineHeight: 36,
      letterSpacing: 0,
    },
    headlineSmall: {
      fontFamily: 'ITC Bengular',
      fontWeight: '700',
      fontSize: 24,
      lineHeight: 32,
      letterSpacing: 0,
    },
    titleLarge: {
      fontFamily: 'Work Sans',
      fontWeight: '600',
      fontSize: 22,
      lineHeight: 28,
      letterSpacing: 0,
    },
    titleMedium: {
      fontFamily: 'Work Sans',
      fontWeight: '600',
      fontSize: 16,
      lineHeight: 24,
      letterSpacing: 0.15,
    },
    titleSmall: {
      fontFamily: 'Work Sans',
      fontWeight: '600',
      fontSize: 14,
      lineHeight: 20,
      letterSpacing: 0.1,
    },
    labelLarge: {
      fontFamily: 'Work Sans',
      fontWeight: '500',
      fontSize: 14,
      lineHeight: 20,
      letterSpacing: 0.1,
    },
    labelMedium: {
      fontFamily: 'Work Sans',
      fontWeight: '500',
      fontSize: 12,
      lineHeight: 16,
      letterSpacing: 0.5,
    },
    labelSmall: {
      fontFamily: 'Work Sans',
      fontWeight: '500',
      fontSize: 11,
      lineHeight: 16,
      letterSpacing: 0.5,
    },
    bodyLarge: {
      fontFamily: 'Work Sans',
      fontWeight: '400',
      fontSize: 16,
      lineHeight: 24,
      letterSpacing: 0.5,
    },
    bodyMedium: {
      fontFamily: 'Work Sans',
      fontWeight: '400',
      fontSize: 14,
      lineHeight: 20,
      letterSpacing: 0.25,
    },
    bodySmall: {
      fontFamily: 'Work Sans',
      fontWeight: '400',
      fontSize: 12,
      lineHeight: 16,
      letterSpacing: 0.4,
    },
  },
};
